spring:
  application:
    name: dynamic-thread-pool-starter

dynamic:
  thread:
    pool:
      registry:
        redis:
          enable: true
          host: 47.98.115.202
          port: 6379
          password: xiaofu
        report-cron: 0/20 * * * * ?
